### ISSUE TITLE
please add feature :)

### ISSUE THREAD

**Issue by n3roGit** [thost96/pimatic-wakeonlan#3]
1. 
i would be nice to usw your addon in roules like:
if button is pressed than wol "00:00:00:00:00:00:"

2.
it would be great to use multiple MACs in one device like:
{
  "class": "WakeOnLanDevice",
  "id": "pc-dad"
{
  "name": "PC-Dad",
  "mac": "11:22:33:44:55:66"
},
{
"name": "PC-Dad2",
  "mac": "11:22:33:44:55:77"
}
}

**Comment by thost96** [comment]
1. -> will be avaible in a future version
2. -> Why do you like to use multiple macs in one device? If you want to wakeup a device which has more than one interface, only one interface is needed to wake it up.

**Comment by n3roGit** [comment]
2.
It would be cool to have only one device (row) in the pimatic dash to start multiple devices like. Pc, server, mediacenter... 

With only one device I have to add one row per device 


:)

**Comment by thost96** [comment]
@n3roGit 
With version 0.2.0, rules can be used with wol or wakeup as command. 

For the moment, you can wakeup multiple devices using a buttonsDevice and a rule. There will be a fix later. ;)
