### ISSUE TITLE
Add license info

### ISSUE THREAD

**Issue by mwittig** [thost96/pimatic-wakeonlan#8]
As part of the next pimatic release it'll be great if all plugin projects and packages contain license infomation, that is:
- add LICENSE file containing the license - if you are happy with GPL-2.0 just copy the license file from the pimatic project
- as part of package.json,
     - add "LICENSE" to "files" to get the LICENSE file included in the npm package
     - add a "license" property with a SPDX-compliant license identifier, for GPL-2.0 this is `"license": "GPL-2.0"`

For more information on SPDX see also https://spdx.org/licenses/

**Comment by thost96** [comment]
License was added in [commit #40](https://github.com/thost96/pimatic-wakeonlan/commit/4fe2cc83d6a80bc587a4a08018fde8bab027c809).
